### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: no sodium in java.library.path

### ISSUE THREAD

**Issue by patsan303** [wireapp/echo-bot#42]
When I complete the add.sh script questions and Wire makes a call to my service it throws this exception:
 java.lang.UnsatisfiedLinkError: no sodium in java.library.path

the add.sh script exits with this error:
{"code":502,"message":"The upstream service returned an invalid response.","label":"bad-gateway"}

I have confirmed that Wire can reach my service as I can see the initial POST to /bots in my logs.

java version: 1.8.0_201
OS: ubuntu 18.04

**Comment by patsan303** [comment]
java 1.8 gives more promising results

**Comment by dkovacevic** [comment]
You need to specify the: `-Djava.library.path=$(LD_LIBRARY_PATH)` when running your java run command.
$(LD_LIBRARY_PATH) is your dir where libsodium.so, libcryptobox.so and libcryptobox-jni.so are

You can find those libs for Ubuntu xenia here:
https://github.com/wireapp/cryptobox4j

or you can run the `make` there which sould (holepully) build those...

**Comment by patsan303** [comment]
thanks, that helped me get it working! Just using the binaries from cryptobox4j on Ubuntu 18.04 failed with this error:

>java.lang.UnsatisfiedLinkError: /home/ubuntu/echo-bot/libs/libcryptobox-jni.so: libcryptobox.so: cannot open shared object file: No such file or directory

but running make and building new binaries worked like a charm!
