### ISSUE TITLE
Trouble adding other participants to conversation

### ISSUE THREAD

**Issue by patsan303** [wireapp/echo-bot#43]
The echo-bot service works for me when I use the add.sh script. But if I try and add any other participants it says "[user] does not want to be added to conversations". I've tried adding other participants before adding the bot to the conversation and after.

**Comment by dkovacevic** [comment]
Only connected users can be added. If you run `add.sh` as user Patrick and you would like to add another user called Dejan then Patrick and Dejan must be connected already.

**Comment by patsan303** [comment]
The users I'm trying to add to the conversation are already connected to me as team members. I can add my personal Wire account to this conversation though with no problems. Only when trying to add my team members do I get this message.

**Comment by dkovacevic** [comment]
If you are using a _team account_ you don't need to mess up with `add.sh`. Just open your _Manage Team_ page, go to _Services_ tab add your service: `<ProviderId>:<ServiceId>`
Then in Wire app: Go to _People picker_, create new Conv, add your colleagues... Open that conv, Add participant, Services, Your Bot...you are done. Easy, no?

**Comment by patsan303** [comment]
great, that works! thanks for the feedback
